

     
 var Web3 = require('web3');    // Checking if Web3 has been injected by the browser (Mist/MetaMask)
  if (typeof web3 !== 'undefined') {
          // Use Mist/MetaMask's provider
          web3 = new Web3(web3.currentProvider);
  } else {
          web3 = new Web3(new Web3.providers.HttpProvider('http://localhost:7545'));
        }

// // Now you can start your app & access web3 freely:
// //Here's how we would access our contract:

  let abi = [
  {
    "constant": true,
    "inputs": [
      {
        "name": "",
        "type": "uint256"
      }
    ],
    "name": "zombies",
    "outputs": [
      {
        "name": "name",
        "type": "string"
      },
      {
        "name": "dna",
        "type": "uint256"
      }
    ],
    "payable": false,
    "stateMutability": "view",
    "type": "function"
  },
  {
    "constant": false,
    "inputs": [
      {
        "name": "_name",
        "type": "string"
      }
    ],
    "name": "createRamdomeZombie",
    "outputs": [],
    "payable": false,
    "stateMutability": "nonpayable",
    "type": "function"
  },
  {
    "anonymous": false,
    "inputs": [
      {
        "indexed": false,
        "name": "zombieId",
        "type": "uint256"
      },
      {
        "indexed": false,
        "name": "name",
        "type": "string"
      },
      {
        "indexed": false,
        "name": "dna",
        "type": "uint256"
      }
    ],
    "name": "NewZombie",
    "type": "event"
  }
]


const button  = document.getElementById('ourButton');

const input  =document.getElementById('nameInput');
/*
abi generated by the complier
*/
const contractAddress = "0xDA0bab807633f07f013f94DD0E6A4F96F8742B53";

const ZombiefactoryContract = web3.eth.contract(abi);

const Zombiefactory = ZombiefactoryContract.at(contractAddress);
// // `ZombieFactory` has access to our contract's public functions and events



button.addEventListener('click',()=>{
  var name = input.value;
  // Call our contract's `createRandomzombie`function
  // Zombiefactory.createRamdomeZombie(name);

  console.log("functioncalled")
});

var event  = ZombiefactoryContract.NewZombie((error,result) => {
  if(error)return;

  console.log(result);
});


